#true=mysql, false=sqlite
usemysql: true
mysql:
 host:
 port: 3306
 database:
 username:
 password:
 prefix: novaguilds_

debug: false
lang: en-en

tabapi:
 enabled: false
 colortags: true
 rankprefix: false

 tabinfo:
  enabled: false
  requirepermissions: false

tagapi:
 enabled: false
 colortags: true
 rankprefix: false
 allycolor:
  enabled: true
  color: "&5"
 guildcolor:
  enabled: true
  color: "&a"
 warcolor:
  enabled: true
  color: "&c"

usevault: true

holographicdisplays:
 enabled: false

#Save period in minutes
saveperiod: 10

chat:
 ally:
  prefix: "!!"
  enabled: true
  colortags: true
  leaderprefix: true
  format: "&6[&5Ally&6] &a{TAG}&8{PLAYERNAME}&6:&r "
  msgprefix: "&6"
 guild:
  prefix: "!"
  enabled: true
  leaderprefix: true
  format: "&6[&7Guild&6] &8{PLAYERNAME}&6:&r "
  msgprefix: "&6"

takeover:
 endercrystal:
  enabled: true
  explosionpower: 50
  #seconds
  time: 100
  #cooldown in seconds
  cooldown: 0.1
  requireguild: false
  requirewar: false

raid:
 enabled: true
 minonline: 1
 minonlineenemy: 1

 #time guild has to rest in seconds (24h)
 timerest: 86400

 #Inactive time after which the raid is over. seconds.
 timeinactive: 10

killing:
 moneyforkill: 5%
 moneyforrevenge: 10%

guild:
 tag: "&a{RANK}{TAG} &r"
 startpoints: 1000
 startmoney: 0
 startlives: 2
 fromspawn: 100
 settings:
  tag:
   color: true
   min: 2
   max: 6
  name:
   min: 4
   max: 10

 killpoints: 5
 deathpoints: 5

 #permissions: novaguilds.group.GROUP
 #there's no need for admin group. novaguilds.group.admin for no items required
 create:
  groups:
   default: #this is default
    money: 0
    items:
     - dirt 1
   vip: #novaguilds.group.vip
    money: 0
    items:
     - cobblestone 5

region:
 #price per block
 pricepb: 1
 createprice: 100
 minsize: 10
 maxsize: 100
 tool:
  item: STICK

 denyinteract:
  - WOODEN_DOOR
  - LEVER
  - DISPENSER
  - STONE_BUTTON
  - WOOD_BUTTON
  - DROPPER
  - HOPPER
  - FENCE_GATE
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - REDSTONE_REPEATER
  - TRAP_DOOR
  - CHEST
  - ANVIL
  - ENCHANTMENT_TABLE
  - WORKBENCH
  - FURNACE
  - DIODE_BLOCK_ON
  - DIODE_BLOCK_OFF
  - WOOD_PLATE
  - STONE_PLATE
  - IRON_PLATE
  - GOLD_PLATE
  - ENDER_CHEST
  - ENDER_PORTAL_FRAME
  - NOTE_BLOCK
  - JUKEBOX
  - BEACON
  - ITEM_FRAME
 denyuse:
  - LAVA_BUCKET
  - WATER_BUCKET
  - BUCKET
  - ITEM_FRAME
 denymobdamage:
  - PIG
  - COW
  - SHEEP
  - HORSE
  - WOLF
  - OCELOT
 denyriding:
  - HORSE